Attendance/Attendance/urls.py
"""
Definition of urls for Attendance.
"""

from datetime import datetime
from django.contrib import admin
from django.urls import include, path, re_path

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    path('', include('app.urls')),
    path('', include('session.urls')),
    path('', include('statistics.urls')),
    path('', include('absence_form.urls')),
    path('', include('student.urls')),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

Attendance/app/urls.py
from datetime import datetime
from django.urls import include, path, re_path
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    path('', app.views.home, name='home'),
    path('contact', app.views.contact, name='contact'),
    path('about', app.views.about, name='about'),
    path('login/',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    path('logout',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
]

Attendance/session/urls.py
from django.urls import include, path, re_path

from . import views

urlpatterns = [
    path('sessions/', views.session_overview, name='session_overview'),
    path('sessions/<int:session_pk>', views.session_detail, name='session_detail'),
    path('sessions/<int:session_pk>/attendance_sheet', views.session_download_attendance_sheet, name='session_download_attendance_sheet'),
    path('sessions/<int:session_pk>/attendance', views.session_taking_attendance, name='session_taking_attendance'),
    path('modules/', views.module_index, name='module_index'),
    path('modules/create', views.module_create, name='module_create'),
    path('modules/<int:module_pk>/', views.module_detail, name="module_detail"),
    path('modules/<int:module_pk>/sessions/create', views.module_create_session, name='module_create_session'),
    path('modules/<int:module_pk>/students/import', views.module_student_import, name="module_student_import"),
    path('modules/<int:module_pk>/attendance/', views.module_attendance_history, name="module_attendance_history"),
]

Attendance/student/urls.py
from django.urls import include, path, re_path

from . import views

urlpatterns = [
    path('students/<str:student_id>', views.student_detail, name='student_detail'),
]

Attendance/session/models.py
from io import BytesIO
from datetime import date, timedelta
from django.db import models
from django.utils import timezone
from django.db.models.fields.related import ManyToManyField
from django.contrib.auth.models import User
from django.db.models import Avg, Count
from django.core.validators import MaxValueValidator, MinValueValidator
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors

from student.models import Student

# Create your models here.

def getyear():
    return timezone.now().year

class Module(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=8)
    academic_year = models.SmallIntegerField(validators=[
        MaxValueValidator(3881),
        MinValueValidator(1881)
    ], default=getyear)
    # todo: should bind to profile in case a user does not have that
    convenors = models.ManyToManyField(User, related_name='convenors', blank=True)
    assistants = models.ManyToManyField(User, related_name='assistants', blank=True)
    students = models.ManyToManyField(Student, blank=True)
    attendance_rate = models.FloatField(
        null=True, editable=False,
        # todo: test
        validators = [MinValueValidator(0.0), MaxValueValidator(1.0)]
    )

    def __str__(self):
        return '{} ({})'.format(self.name, self.academic_year)

    # returns: conflicted Student objects
    def batch_enroll_from_csv(self, student_reader):
        # todo: make column name more explicit
        # the students in the uploaded list can be:
        # - not in the student db table
        # - the same as in the table
        # - same id with different name
        uploaded_dict = {
            row[0]: Student(
                student_id=row[0],
                first_name=row[1],
                last_name=row[2],
            )
            for row in student_reader
        }
        # find out conflicts -> report
        # find out identical -> add to student list
        # find out new students -> create & add
        conflicts_models = []
        identical_dict = {}
        # fetch old information and compare
        existing_students = Student.objects.filter(student_id__in=uploaded_dict.keys())
        for s in existing_students:
            new_info = uploaded_dict.get(s.student_id)
            # the existing student must also be in the uploaded_dict
            assert(new_info is not None)
            # conflicts
            if s.first_name != new_info.first_name or s.last_name != new_info.last_name:
                conflicts_models.append(s)
            # exactly the same
            else:
                identical_dict[s.student_id] = new_info

        if not conflicts_models:
            # if their is no conflict, uploaded_dict = new_student_models + identical_models
            new_student_models = [uploaded_dict[id] for id in set(uploaded_dict) - set(identical_dict)]
            Student.objects.bulk_create(new_student_models)
            new_students_saved = Student.objects.filter(student_id__in=uploaded_dict.keys())
            self.students.add(*new_students_saved)

        # todo: display conflicts to user
        return conflicts_models

    def update_attendance_rate(self):
        """Calculate the average attendance rate from all sessions whose attendance records are completed.
        """
        session_avg_rate = self.session_set\
            .filter(attendance_rate__isnull=False)\
            .aggregate(Avg('attendance_rate'))
        self.attendance_rate = session_avg_rate['attendance_rate__avg']
        self.save()


class Session(models.Model):
    module = models.ForeignKey(Module, on_delete=models.PROTECT)
    time = models.DateTimeField(default=timezone.now)
    duration = models.DurationField(default=timedelta(hours=1))
    place = models.CharField(max_length=127, blank=True)

    LAB = 'LA'
    LECTURE = 'LE'
    SESSION_TYPES = (
        (LAB, 'Lab'),
        (LECTURE, 'Lecture'),
    )
    type = models.CharField(max_length=2, choices=SESSION_TYPES)

    # only not null after taking attendance
    attendance_rate = models.FloatField(
        null=True, editable=False,
        validators = [MinValueValidator(0.0), MaxValueValidator(1.0)]
    )

    def __str__(self):
        return '{} @ {}'.format(self.time.strftime("%b %d %H:%M"), self.place)

    # todo: write a test
    def get_signature_sheet_pdf(self):
        """Generate a signature sheet pdf from the module student list.
        """
        assert(self.attendance_rate == None)

        buffer = BytesIO()
        # set some characteristics for pdf document
        doc = SimpleDocTemplate(
            buffer,
            rightMargin=30,
            leftMargin=40,
            topMargin=40,
            bottomMargin=30,
            pagesize=A4
        )
        # a collection of styles offer by the library
        styles = getSampleStyleSheet()
        # add custom paragraph style
        styles.add(ParagraphStyle(name="TableHeader", fontSize=11, alignment=TA_CENTER))
        # list used for elements added into document
        data = []
        data.append(Paragraph("{0} Signature Sheet".format(self.module), styles['h2']))
        data.append(Paragraph("Time: {0} Place: {1}".format(
            self.time.strftime('%a, %d %b %Y %H:%M'),
            self.place
        ), styles['h2']))
        # insert a blank space
        data.append(Spacer(1, 12))
        table_data = []
        # table header
        table_data.append([
            Paragraph('Student Id', styles['TableHeader']),
            Paragraph('First Name', styles['TableHeader']),
            Paragraph('Last Name', styles['TableHeader']),
            Paragraph('Signature', styles['TableHeader']),
        ])
        attendees = self.module.students.all()
        for a in attendees:
            # add a row to table
            table_data.append([
                a.student_id,
                a.first_name,
                a.last_name,
                '',
            ])
        # create table
        wh_table = Table(table_data, colWidths=[doc.width/4.0]*4)
        wh_table.hAlign = 'LEFT'
        wh_table.setStyle(TableStyle(
            [('INNERGRID', (0, 0), (-1, -1), 0.25, colors.black),
             ('BOX', (0, 0), (-1, -1), 0.5, colors.black),
             ('VALIGN', (0, 0), (-1, 0), 'MIDDLE'),
             ('BACKGROUND', (0, 0), (-1, 0), colors.gray)]))
        data.append(wh_table)
        # create document
        doc.build(data)
        pdf = buffer.getvalue()
        buffer.close()
        return pdf

    def update_attendance_rate(self):
        """Calculate the attendance rate from the attendance records."""

        total_attendees = self.attendee_set.all().count()
        attended = self.attendee_set\
            .filter(presented=True)\
            .count()
        self.attendance_rate = attended / total_attendees
        assert(self.attendance_rate != None)
        self.save()

    def is_affected_by_application_detail(self, detail):
        if detail.module != self.module:
            return False
        if detail.from_date < self.time:
            return True if detail.to_date > self.time else False
        else:
            return True if detail.from_date <= self.time + self.duration else False


class Attendee(models.Model):
    session = models.ForeignKey(Session, on_delete=models.PROTECT)
    student = models.ForeignKey(Student, on_delete=models.PROTECT)
    presented = models.BooleanField(default=False)
    comment = models.TextField(blank=True)

    class Meta:
        unique_together = ('session', 'student')

    # todo: potential performance issue when amount entries are large
    def __str__(self):
        return '{} from {}'.format(self.student.get_full_name(), self.session.module)

Attendance/student/models.py
from django.db import models

# Create your models here.

def trimed_title_case(str):
    return " ".join(str.split()).title()

class Student(models.Model):
    student_id = models.CharField(max_length=16, unique=True)
    first_name = models.CharField(max_length=127)
    last_name = models.CharField(max_length=127)
    degree_name = models.CharField(max_length=255, blank=True)
    GENDERS = (
        ('F', 'Female'),
        ('M', 'Male'),
    )
    gender = models.CharField(max_length=2, choices=GENDERS, blank=True)
    email = models.EmailField(blank=True)

    class Meta:
        indexes = [
            # the student id is use for searching
            models.Index(fields=['student_id']),
        ]

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def __str__(self):
        return '{} ({})'.format(self.get_full_name(), self.student_id)

    def save(self, *args, **kwargs):
        """The method is overridden to sanitize the data"""
        self.student_id = self.student_id.strip()
        self.first_name = trimed_title_case(self.first_name)
        self.last_name = trimed_title_case(self.last_name)

        super().save(*args, **kwargs)

Attendance/session/forms.py
from django.forms import ModelForm
from django import forms
import datetime
from .models import *

class ModuleCreateForm(ModelForm):
    class Meta:
        model = Module
        exclude = ['students', 'attendance_rate']

class SessionCreateForm(ModelForm):
    repeat_for_weeks = forms.IntegerField(min_value=1, initial=1)

    class Meta:
        model = Session
        fields = ['time', 'duration', 'place', 'type', 'repeat_for_weeks']

Attendance/student/views.py
from django.shortcuts import render, Http404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden

from .models import Student
from session.models import *
from absence_form.models import *

# todo: permission
def get_student_by_id(student_id):
    try:
        s = Student.objects.get(student_id=student_id)
    except Student.DoesNotExist:
        raise Http404("Student does not exist")
    return s

@login_required
def student_detail(request, student_id):
    if not request.user.has_perm('student.view'):
        return HttpResponseForbidden()

    s = get_student_by_id(student_id)

    # participated modules
    modules = Module.objects.filter(students__student_id=student_id)

    # involved sessions
    attendances = Attendee.objects.filter(student=s)\
        .prefetch_related('session')\
        .order_by('-session__time')

    # affected applications
    applications = Application.objects.filter(student=s)

    context = {
        'title': s,
        'student': s,
        'modules': modules,
        'attendances': attendances,
        'applications': applications,
    }

    return render(request, 'student/detail.html', context)

Attendance/session/templates/module/attendance_history.html
{% extends "app/layout.html" %}

{% load staticfiles %}
{% load dict_access %}
{% load attendance_helper %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'module/styles/attendance_history.css' %}"/>
<style>
    #attendance-table {
        width: auto;
    }
</style>
{% endblock %}

{% block content %}
<h4>{{ module }}</h4>
<div class="table-responsive">
    <table id="attendance-table">
        <thead>
        <tr>
            <th></th>
            <th></th>
            {% for se in sessions %}
            <th class="rotate" scope="col">
                <div>
                    <span><a href="{% url 'session_detail' se.pk %}">{{ se }}</a></span>
                </div>
            </th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for st in students %}
        <tr>
            <th scope="row"><a href="{% url 'student_detail' st.student_id %}">{{ st.student_id }}</a></th>
            <th scope="row">{{ st.get_full_name }}</th>
            {% for se in sessions %}
            {% tuple_key cells se.pk st.pk as a %}
            <td class="{% attendance_style a student_to_app_details %}"></td>
            {% endfor %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block scripts %}
<script>
    $('#attendance-history td').click(function(e) {
        $('#attendance-detail').text($(e.target).data('student-id'));
    })
</script>
{% endblock %}

Attendance/session/templates/module/create.html
{% extends "app/layout.html" %}

{% load material_form %}

{% block content %}
<div class="container expand-on-small-only">
    <div class="row valign change-form">
        <div class="col s12 m8 offset-m2 l8 offset-l2">
            <div class="card">
                <form action="{% url 'module_create' %}" method="post">
                    {% csrf_token %}
                    <div class="card-content">
                        <span class="card-title grey-text text-darken-2">Create module</span>
                        {% form form=form %}{% endform %}
                    </div>
                    <div class="card-action">
                        <div class="right-align">
                            <button type="submit" name="submit" class="waves-effect waves-light btn">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Attendance/session/templates/module/detail.html
{% extends "app/layout.html" %}

{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'module/styles/jsgrid.min.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'module/styles/jsgrid-theme.min.css' %}"/>
{% endblock %}

{% block content %}
<div class="container">
    <h4>{{ module }}</h4>
    <a class="waves-effect waves-light btn" href="{% url 'module_attendance_history' module.pk %}">View Attendance History</a>
    <div class="row">
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s4"><a href="#session_list">Sessions</a></li>
                <li class="tab col s4"><a href="#student_list">Students</a></li>
                <li class="tab col s4"><a href="#student_import">Import</a></li>
            </ul>
        </div>
        <div id="session_list" class="col s12">
            <div id="session_list_wrapper">
                <a class="waves-effect waves-light btn" href="{% url 'module_create_session' module.pk %}">Add Sessions</a>
                {% include 'module/detail/session_list.html' %}
            </div>
        </div>
        <div id="student_list" class="col s12">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Student Id</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                </tr>
                </thead>
                <tbody>
                {% for s in module.students.all %}
                <tr>
                    <th scope="row"><a href="{% url 'student_detail' s.student_id %}">{{ s.student_id }}</a></th>
                    <td>{{ s.first_name }}</td>
                    <td>{{ s.last_name }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div id="student_import" class="col s12">
            {% include 'module/detail/student_import.html' %}
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'module/scripts/papaparse.min.js' %}"></script>
<script src="{% static 'module/scripts/jsgrid.min.js' %}"></script>
<script>
    var postUrl = "{% url 'module_student_import' module.pk %}";
    $('.tabs').tabs();
</script>
<script src="{% static 'module/scripts/student_import.js' %}"></script>
<script>
    var session_list = new Vue({
        el: '#session_list_wrapper',
        data: {
            items: [
            {% for s in module.session_set.all %} {
                "module": "{{ s.module }}",
                "time": "{{ s.time }}",
                "duration": "{{ s.duration }}",
                "place": "{{ s.place }}",
                "type": "{{ s.get_type_display }}",
                "attendance_rate": {% if s.attendance_rate %}{{ s.attendance_rate }}{% else %}null{% endif %},
                "session_link": "{% url 'session_detail' s.pk %}",
                "sheet_download": "{% url 'session_download_attendance_sheet' s.pk %}"
            }, {% endfor %}
            ]
        },
        methods: {
            navigate(url) {
                window.location = url;
            }
        }
    });
</script>
{% endblock %}

Attendance/session/templates/module/index.html
{% extends "app/layout.html" %}

{% load staticfiles %}
{% load attendance_helper %}

{% block content %}
<div class="container">
    <table>
        <thead>
        <tr>
            <th scope="col">Module</th>
            <th scope="col">Attendance Rate</th>
        </tr>
        </thead>
        <tbody>
        {% for m in modules %}
        <tr>
            <td>
                <a href="{% url 'module_detail' m.pk %}" title="">{{ m }}</a>
            </td>
            <td>
                {# todo: deal with null attendance rate #}
                <div class="progress">
                    <div class="determinate" style="width: {% widthratio m.attendance_rate 1 100 %}%"></div>
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<div class="fixed-action-btn">
    <a class="btn-floating btn-large red" href="{% url 'module_create' %}">
        <i class="large material-icons">add</i>
    </a>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function(){
        $('.fixed-action-btn').floatingActionButton();
    });
</script>
{% endblock %}

Attendance/session/templates/module/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/table.css' %}" />

    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Application name</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">module</a></li>
                    <li><a href="{% url 'about' %}">session</a></li>
                    <li><a href="{% url 'contact' %}">EC</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

Attendance/session/templates/module/module.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

</body>
</html>

Attendance/session/templates/module/session.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

</body>
</html>

Attendance/session/templates/module/students.html
{% extends "app/layout.html" %}

{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'module/styles/jsgrid.min.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'module/styles/jsgrid-theme.min.css' %}"/>
{% endblock %}

{% block content %}
<ul class="nav nav-tabs" id="module-info-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="student-list-tab" data-toggle="tab" href="#student-list" role="tab" aria-controls="student-list" aria-selected="true">Students</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="student-import-tab" data-toggle="tab" href="#student-import" role="tab" aria-controls="student-import" aria-selected="false">Import</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="student-list" role="tabpanel" aria-labelledby="student-list-tab">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Student Id</th>
                <th scope="col">First Name</th> 
                <th scope="col">Last Name</th>
            </tr>
            </thead>
            <tbody>
            {% for s in module.students.all %}
            <tr>
                <th scope="row">{{ s.student_id }}</th>
                <td>{{ s.first_name }}</td>
                <td>{{ s.last_name }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="student-import" role="tabpanel" aria-labelledby="student-import-tab">
    {% include 'module/student_import.html' %}
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'module/scripts/papaparse.min.js' %}"></script>
<script src="{% static 'module/scripts/jsgrid.min.js' %}"></script>
<script src="{% static 'module/scripts/student_import.js' %}"></script>
{% endblock %}